sonar.projectKey=abdullahhanif-001_elite-ebpf-telemetry
sonar.organization=abdullahhanif-001
sonar.sources=.
# Keep CI scan scope aligned with Automatic Analysis.
sonar.exclusions=**/bpf/headers/**,pkg/skoop/**,pkg/controller/**,cmd/skoop/**,cmd/collector/**,cmd/controller/**,webui/**,test/**,tools/bpf2go/**,tools/builder/**
sonar.cpd.exclusions=**/bpf_bpfel*.go,**/bpf_bpfeb*.go,**/pkg/exporter/testbtf/**
sonar.sca.exclusions=pkg/skoop/go.mod,pkg/controller/go.mod,cmd/skoop/go.mod,cmd/collector/go.mod,cmd/controller/go.mod,test/skoop/go.mod,webui/go.mod,tools/bpf2go/go.mod
sonar.go.coverage.reportPaths=coverage.out
sonar.coverage.exclusions=**/*_test.go,**/vendor/**,webui/node_modules/**,test/skoop/e2e/**
