apiVersion: v1
name: elite-ebpf
description: Elite eBPF — zero-instrumentation kernel telemetry by Abdullah Hanif
type: application
annotations:
  category: Analytics
  licenses: Apache-2.0
version: 1.0.0
appVersion: 1.0.0
keywords:
  - elite
  - elite-ebpf
  - kubernetes
  - prometheus
  - eBPF
  - monitoring
home: https://github.com/abdullahanifpro111-spec/elite-ebpf
sources:
  - https://github.com/abdullahanifpro111-spec/elite-ebpf
maintainers:
- name: Abdullah Hanif
  url: https://github.com/abdullahanifpro111-spec
