name: build

on:
  push:
    branches: [main]
    tags:
      - 'v*'
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io
  OWNER: abdullahanifpro111-spec/elite-ebpf

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.after }}
  cancel-in-progress: true

jobs:
  build-skoop:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Docker meta agent
        id: meta-agent
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.OWNER }}/agent
          tags: |
            type=raw,value={{date 'YYYYMMDD'}}-{{sha}}
            type=semver,pattern={{version}}
            type=semver,pattern={{raw}}
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Docker meta controller
        id: meta-controller
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.OWNER }}/controller
          tags: |
            type=raw,value={{date 'YYYYMMDD'}}-{{sha}}
            type=semver,pattern={{version}}
            type=semver,pattern={{raw}}
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Login to DockerHub
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        if: ${{ github.event_name != 'pull_request' && github.event.action != 'unassigned' && github.repository == 'abdullahanifpro111-spec/elite-ebpf' }}

      - name: Go Build Cache for Docker
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        with:
          path: go-build-cache
          key: ${{ runner.os }}-go-build-cache-${{ hashFiles('**/go.sum') }}
      - name: inject go-build-cache into docker
        # v1 was composed of two actions: "inject" and "extract".
        # v2 is unified to a single action.
        uses: reproducible-containers/buildkit-cache-dance@4cbeee199780e776bc5704004daea271aaed1d1b # v2.1.2
        with:
          cache-source: go-build-cache

      - name: Build and push agent
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' && github.repository == 'abdullahanifpro111-spec/elite-ebpf' }}
          tags: ${{ steps.meta-agent.outputs.tags }}
          target: agent
          labels: ${{ steps.meta-agent.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build and push controller
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' && github.repository == 'abdullahanifpro111-spec/elite-ebpf' }}
          tags: ${{ steps.meta-controller.outputs.tags }}
          target: controller
          labels: ${{ steps.meta-controller.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
