{
 "title": "skoop-exporter-pods",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(k8s_namespace)" } },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values({k8s_namespace=\"$namespace\"},k8s_pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Network Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Network Device RX bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(elite_netdev_rxbytes{k8s_namespace=\"$namespace\", k8s_pod=\"$pod\"}[1m])",
     "legendFormat": "rx bytes"
    }
   ]
  },
  {
   "title": "Network Device TX bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(elite_netdev_txbytes{k8s_namespace=\"$namespace\", k8s_pod=\"$pod\"}[1m])",
     "legendFormat": "tx bytes"
    }
   ]
  },
  {
   "title": "Network Device TX errors(times)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(elite_netdev_txerrors{k8s_namespace=\"$namespace\", k8s_pod=\"$pod\"}[1m])",
     "legendFormat": "tx errors"
    }
   ]
  },
  {
   "title": "Network Device RX errors(times)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(elite_netdev_rxerrors{k8s_namespace=\"$namespace\", k8s_pod=\"$pod\"}[1m])",
     "legendFormat": "rx errors"
    }
   ]
  },
  {
   "title": "Network Device TX Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(elite_netdev_txpackets{k8s_namespace=\"$namespace\", k8s_pod=\"$pod\"}[1m])",
     "legendFormat": "tx packets"
    }
   ]
  },
  {
   "title": "Network Device RX Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(elite_netdev_rxpackets{k8s_namespace=\"$namespace\", k8s_pod=\"$pod\"}[1m])",
     "legendFormat": "rx packets"
    }
   ]
  },
  { "title": "TCP Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "TCP Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "elite_tcpsummary_tcptimewaitconn{k8s_namespace=\"$namespace\", k8s_pod=\"$pod\"}",
     "legendFormat": "timewait"
    },
    {
     "expr": "elite_tcpsummary_tcpestablishedconn{k8s_namespace=\"$namespace\", k8s_pod=\"$pod\"}",
     "legendFormat": "established"
    },
    {
     "expr": "elite_tcpsummary_tcpclosewaitconn{k8s_namespace=\"$namespace\", k8s_pod=\"$pod\"}",
     "legendFormat": "closewait"
    },
    {
     "expr": "elite_tcpsummary_tcpsynsentconn{k8s_namespace=\"$namespace\", k8s_pod=\"$pod\"}",
     "legendFormat": "syn sent"
    },
    {
     "expr": "elite_tcpsummary_tcpsynrecvconn{k8s_namespace=\"$namespace\", k8s_pod=\"$pod\"}",
     "legendFormat": "syn recv"
    }
   ]
  },
  {
   "title": "TCP Socket Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "elite_sock_inuse{k8s_namespace=\"$namespace\", k8s_pod=\"$pod\"}+elite_sock_orphan{k8s_namespace=\"$namespace\", k8s_pod=\"$pod\"}",
     "legendFormat": "Hostnet"
    },
    {
     "expr": "elite_sock_inuse{k8s_node=\"$node\",k8s_pod!=\"\"}+elite_sock_orphan{k8s_node=\"$node\", k8s_pod!=\"\"}",
     "legendFormat": "{{k8s_namespace}}/{{k8s_pod}}"
    }
   ]
  },
  { "title": "TCPExt", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "TCP Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "elite_tcpsummary_tcptxqueue{k8s_namespace=\"$namespace\", k8s_pod=\"$pod\"}",
     "legendFormat": "TX Queue"
    },
    {
     "expr": "elite_tcpsummary_tcprxqueue{k8s_namespace=\"$namespace\", k8s_pod=\"$pod\"}",
     "legendFormat": "RX Queue"
    }
   ]
  },
  {
   "title": "TCP Opens",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(elite_tcp_passiveopens{k8s_namespace=\"$namespace\", k8s_pod=\"$pod\"}[1m])",
     "legendFormat": "passive opens"
    },
    {
     "expr": "rate(elite_tcp_activeopens{k8s_namespace=\"$namespace\", k8s_pod=\"$pod\"}[1m])",
     "legendFormat": "active opens"
    }
   ]
  },
  {
   "title": "TCPListenDrops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "rate(elite_tcpext_listendrops{k8s_namespace=\"$namespace\", k8s_pod=\"$pod\"}[1m])",
     "legendFormat": "listen drops"
    }
   ]
  },
  {
   "title": "ListenOverflows",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "rate(elite_tcpext_listenoverflows{k8s_namespace=\"$namespace\", k8s_pod=\"$pod\"}[1m])",
     "legendFormat": "listen overflows"
    }
   ]
  },
  {
   "title": "TCPSynRetrans",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "rate(elite_tcpext_tcpsynretrans{k8s_namespace=\"$namespace\", k8s_pod=\"$pod\"}[1m])",
     "legendFormat": "syn retrans"
    }
   ]
  },
  {
   "title": "TCPRcvQDrop",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "rate(elite_tcpext_tcprcvqdrop{k8s_namespace=\"$namespace\", k8s_pod=\"$pod\"}[1m])",
     "legendFormat": "receive queue drops"
    }
   ]
  },
  {
   "title": "TCP Memory Alloc Fail",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "rate(elite_tcpext_pfmemallocdrop{k8s_namespace=\"$namespace\", k8s_pod=\"$pod\"}[1m])",
     "legendFormat": "memory alloc fail"
    }
   ]
  },
  {
   "title": "TCPBacklogDrop",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "rate(elite_tcpext_tcpbacklogdrop{k8s_namespace=\"$namespace\", k8s_pod=\"$pod\"}[1m])",
     "legendFormat": "backlog drops"
    }
   ]
  },
  { "title": "UDP Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "UDP RCV-Buffer exceeded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(elite_udp_rcvbuferrors{k8s_namespace=\"$namespace\", k8s_pod=\"$pod\"}[1m])",
     "legendFormat": "receive buffer errors"
    }
   ]
  },
  {
   "title": "UDP SND-Buffer exceeded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(elite_udp_sndbuferrors{k8s_namespace=\"$namespace\", k8s_pod=\"$pod\"}[1m])",
     "legendFormat": "send buffer errors"
    }
   ]
  },
  {
   "title": "UDP No-Ports",
   "type": "timeseries",
   "description": "如果出现dns超时，您需要关注这个指标，通常在Serever返回较慢的情况，例如公网DNS场景，回包慢于用户设定超时，会出现这个情况。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(elite_udp_noports{k8s_namespace=\"$namespace\", k8s_pod=\"$pod\"}[1m])",
     "legendFormat": "no port times"
    }
   ]
  },
  {
   "title": "UDP In Error",
   "type": "timeseries",
   "description": "在dns超时场景中，如果查询结果的udp在validate中被丢弃，由于没有重传机制，因此会直接导致超时。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(elite_udp_inerrors{k8s_namespace=\"$namespace\", k8s_pod=\"$pod\"}[1m])",
     "legendFormat": "input errors"
    }
   ]
  }
 ]
}